server:
  logLevel: debug

template:
  title: Trifid Playground

globals:
  datasetBaseUrl: https://ld.zazuko.com/
  sparqlEndpoint:
    url: env:SPARQL_ENDPOINT_URL
    username: env:SPARQL_ENDPOINT_USER
    password: env:SPARQL_ENDPOINT_PASSWORD

middlewares:
  welcome:
    module: trifid-core/middlewares/view.js
    order: 0
    paths: /
    methods: GET
    config:
      path: views/welcome.hbs

  parameters:
    module: trifid-core/middlewares/view.js
    order: 0
    paths: /parameters
    methods: GET
    config:
      path: views/parameters.hbs

  rewrite:
    module: trifid-core/middlewares/rewrite.js

  entity-renderer:
    module: "@zazuko/trifid-renderer-entity"
    config:
      path: views/entity.hbs
      labelLoader:
        labelNamespaces:
          - https://ld.zazuko.com
        chunkSize: 30
        concurrency: 2
        timeout: 1000

  yasgui:
    module: trifid-plugin-yasgui
    paths: /sparql
    config:
      urlShortener: https://s.zazuko.com/api/v1/shorten

  sparql-proxy:
    module: "@zazuko/trifid-plugin-sparql-proxy"
    paths: /query
    config:
      queryOperation: postQueryUrlencoded
      cache:
        prefix: env:SPARQL_PROXY_CACHE_PREFIX
        url: env:SPARQL_PROXY_CACHE_URL
        ttl: env:SPARQL_PROXY_CACHE_TTL
        clearAtStartup: env:SPARQL_PROXY_CACHE_CLEAR_AT_STARTUP

  sparql-handler:
    module: "trifid-handler-sparql"
    config:
      resourceExistsQuery: "ASK { GRAPH ?g { <${iri}> ?p ?o } }"
      resourceGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <${iri}>"
      containerExistsQuery: 'ASK { GRAPH ?g { ?s a ?o. FILTER REGEX(STR(?s), "^${iri}") } }'
