server:
  logLevel: info

template:
  title: Trifid Playground

globals:
  datasetBaseUrl: https://ld.zazuko.com/
  endpoints:
    default:
      url: /query

plugins:
  welcome:
    module: trifid-core/plugins/view.js
    paths: /
    methods: GET
    config:
      path: views/welcome.hbs

  parameters:
    module: trifid-core/plugins/view.js
    paths:
      - /parameters
      - /parameters/
    methods: GET
    config:
      path: views/parameters.hbs

  entity-renderer:
    module: "@zazuko/trifid-entity-renderer"
    config:
      followRedirects: true
      resourceExistsQuery: "ASK { GRAPH ?g { <{{iri}}> ?p ?o } }"
      resourceGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <{{iri}}>"
      containerExistsQuery: 'ASK { GRAPH ?g { ?s a ?o. FILTER REGEX(STR(?s), "^{{iri}}") } }'
      labelLoader:
        chunkSize: 30
        concurrency: 2
        timeout: 1000

  yasgui:
    module: trifid-plugin-yasgui
    paths:
      - /sparql
      - /sparql/
    config:
      urlShortener: https://s.zazuko.com/api/v1/shorten

  sparql-proxy:
    module: "@zazuko/trifid-plugin-sparql-proxy"
    paths:
      - /query
      - /query/
    config:
      endpointUrl: env:SPARQL_ENDPOINT_URL
      username: env:SPARQL_ENDPOINT_USER
      password: env:SPARQL_ENDPOINT_PASSWORD
