apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trifid
  annotations:
    kubernetes.io/tls-acme: "true"
    external-dns.alpha.kubernetes.io/hostname: ld-zazuko-com.zazukoians.org
spec:
  tls:
  - secretName: ld-zazuko-com-cert
    hosts:
    - ld.zazuko.com
  rules:
  - host: ld.zazuko.com
    http:
      paths:
      - path: /
        backend:
          serviceName: trifid
          servicePort: 80
